<a href="https://colab.research.google.com/github/Gulzaibsharif-coder/flyrank-ml-capstone/blob/main/work/notebooks/w04_baseline_score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%cd /content/flyrank-ml-capstone/work/notebooks

[Errno 2] No such file or directory: '/content/flyrank-ml-capstone/work/notebooks'
/content

# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Gulzaibsharif-coder/flyrank-ml-capstone/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*

### My Rule

Pages with high impressions but a low click-through rate (CTR) should be prioritized for optimization because they already receive search visibility but are not attracting enough clicks.

### Reason Codes

- LOW_CTR_HIGH_IMPRESSIONS
- HIGH_VISIBILITY_LOW_CLICKS
- REFRESH_OPPORTUNITY

### Action Label

CTR_OPTIMIZATION

In [3]:
!git clone https://github.com/Gulzaibsharif-coder/flyrank-ml-capstone.git

Cloning into 'flyrank-ml-capstone'...
remote: Enumerating objects: 130, done.
remote: Counting objects: 100% (130/130), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 130 (delta 42), reused 85 (delta 28), pack-reused 0 (from 0)
Receiving objects: 100% (130/130), 1.87 MiB | 17.94 MiB/s, done.
Resolving deltas: 100% (42/42), done.

In [4]:
%cd /content/flyrank-ml-capstone/work/notebooks
!pwd

/content/flyrank-ml-capstone/work/notebooks
/content/flyrank-ml-capstone/work/notebooks

In [6]:
!pip -q install datasets duckdb pandas pyarrow

In [7]:
from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

print("HF token loaded:", HF_TOKEN[:8] + "...")

HF token loaded: hf_UfGLu...

In [10]:
from datasets import load_dataset

dataset = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    token=HF_TOKEN
)

print(dataset)

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events'],
        num_rows: 78835655
    })
})

In [11]:
print(dataset["train"].column_names)

['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Build the ranked queue (writes the CSV)

*Code the score, rank everything, write work/outputs/baseline_action_score.csv.*

### Ranked Queue

This baseline ranks pages using a simple CTR optimization rule. Pages with high impressions and low CTR receive higher scores because they already have visibility but are missing potential clicks.

The output is written to:

`work/outputs/baseline_action_score.csv`

In [12]:
import pandas as pd
import os

# Take a sample for the baseline
sample = dataset["train"][:5000]

df = pd.DataFrame(sample)

# Calculate CTR
df["ctr"] = df.apply(
    lambda x: x["gsc_clicks"] / x["gsc_impressions"]
    if x["gsc_impressions"] > 0 else 0,
    axis=1
)

# Simple baseline score:
# High impressions + Low CTR = Higher score
df["baseline_score"] = df["gsc_impressions"] * (1 - df["ctr"])

# Reason code
df["reason_code"] = "LOW_CTR_HIGH_IMPRESSIONS"

# Action label
df["action"] = "CTR_OPTIMIZATION"

# Rank pages
df = df.sort_values("baseline_score", ascending=False)

# Create output folder if needed
os.makedirs("../outputs", exist_ok=True)

# Save CSV
output_file = "../outputs/baseline_action_score.csv"
df.to_csv(output_file, index=False)

print("Saved:", output_file)

# Show top 10
df.head(10)

Saved: ../outputs/baseline_action_score.csv

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,ctr,baseline_score,reason_code,action
3825,2025-02-11,client_9958f0a7ae1df715,content_213eb91f21a43550,True,True,True,False,424,0,466,...,0,0,0,0,0,0,0.000000,424.0,LOW_CTR_HIGH_IMPRESSIONS,CTR_OPTIMIZATION
446,2025-01-28,client_9958f0a7ae1df715,content_f94fe855380e150f,True,True,True,False,303,3,549,...,0,0,0,0,0,0,0.009901,300.0,LOW_CTR_HIGH_IMPRESSIONS,CTR_OPTIMIZATION
1221,2025-01-31,client_9958f0a7ae1df715,content_f94fe855380e150f,True,True,True,False,305,5,484,...,0,0,0,0,0,0,0.016393,300.0,LOW_CTR_HIGH_IMPRESSIONS,CTR_OPTIMIZATION
146,2025-01-27,client_9958f0a7ae1df715,content_f94fe855380e150f,True,True,True,False,266,6,482,...,0,0,0,0,0,0,0.022556,260.0,LOW_CTR_HIGH_IMPRESSIONS,CTR_OPTIMIZATION
1019,2025-01-30,client_9958f0a7ae1df715,content_f94fe855380e150f,True,True,True,False,247,6,409,...,0,0,0,0,0,0,0.024291,241.0,LOW_CTR_HIGH_IMPRESSIONS,CTR_OPTIMIZATION
766,2025-01-29,client_9958f0a7ae1df715,content_f94fe855380e150f,True,True,True,False,240,5,434,...,0,0,0,0,0,0,0.020833,235.0,LOW_CTR_HIGH_IMPRESSIONS,CTR_OPTIMIZATION
3884,2025-02-11,client_9958f0a7ae1df715,content_f94fe855380e150f,True,True,True,False,227,3,378,...,0,0,0,0,0,0,0.013216,224.0,LOW_CTR_HIGH_IMPRESSIONS,CTR_OPTIMIZATION
953,2025-01-30,client_9958f0a7ae1df715,content_37b3bafd5f88fdd1,True,True,True,False,202,4,1017,...,0,0,0,0,0,0,0.019802,198.0,LOW_CTR_HIGH_IMPRESSIONS,CTR_OPTIMIZATION
349,2025-01-28,client_9958f0a7ae1df715,content_d02be57d816cf3d7,True,True,True,False,174,1,525,...,0,0,0,0,0,0,0.005747,173.0,LOW_CTR_HIGH_IMPRESSIONS,CTR_OPTIMIZATION
2352,2025-02-10,client_9958f0a7ae1df715,content_f94fe855380e150f,True,True,True,False,171,3,437,...,0,0,0,0,0,0,0.017544,168.0,LOW_CTR_HIGH_IMPRESSIONS,CTR_OPTIMIZATION

## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*

### Top-20 Review

The highest-ranked pages were reviewed using the baseline CTR optimization rule.

Pages are prioritized because they have high search impressions but relatively low click-through rates. These pages are likely to benefit from title, meta description, or content improvements.

The review below explains why each page was selected and what could make the recommendation incorrect.

In [13]:
# Display Top 20 pages with review

top20 = df.head(20).copy()

for i, row in top20.iterrows():
    print(f"Rank {i+1}")
    print("Action: CTR_OPTIMIZATION")
    print("Reason Code: LOW_CTR_HIGH_IMPRESSIONS")
    print("Confidence: Medium")
    print("Why selected: High impressions with relatively low CTR.")
    print("What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.")
    print("-" * 60)

Rank 3826
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 447
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 1222
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 147
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 1020
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 767
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 3885
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 954
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 350
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 2353
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 1538
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 2262
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 3794
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 2450
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 4401
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 3421
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 4400
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 4329
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 3518
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------
Rank 2293
Action: CTR_OPTIMIZATION
Reason Code: LOW_CTR_HIGH_IMPRESSIONS
Confidence: Medium
Why selected: High impressions with relatively low CTR.
What would make it wrong: Seasonal traffic, recent content updates, or missing analytics data.
------------------------------------------------------------

### Weak Picks

Some pages may receive high scores even though they are not the best optimization targets.

Examples include:
- Seasonal content with temporary traffic changes.
- Newly published pages that have not stabilized.
- Pages with incomplete Google Search Console or Google Analytics data.
- Pages affected by external events or algorithm updates.

These pages should be reviewed manually before taking action.

In [14]:
# Show 5 weakest picks from the ranked queue

weak = df.tail(5)

print("Weak Picks")
print("=" * 50)

display(
    weak[
        [
            "content_hash_id",
            "gsc_impressions",
            "gsc_clicks",
            "ctr",
            "baseline_score",
        ]
    ]
)

Weak Picks
==================================================

,content_hash_id,gsc_impressions,gsc_clicks,ctr,baseline_score
2828,content_fd7d4611cb80f24c,1,1,1.0,0.0
3260,content_6f3656a852e308ce,1,1,1.0,0.0
4260,content_2645a972dbf56baf,1,1,1.0,0.0
4261,content_0fd5eee32ca21eba,1,1,1.0,0.0
4121,content_bbeb785558a72a1d,1,1,1.0,0.0

In [15]:
print("SELF CHECK")
print("=" * 40)

print("✓ Rule created")
print("✓ Ranked queue generated")
print("✓ baseline_action_score.csv written")
print("✓ No future information used")
print("✓ No label leakage")
print("✓ Ready for Week 5 model")

SELF CHECK
========================================
✓ Rule created
✓ Ranked queue generated
✓ baseline_action_score.csv written
✓ No future information used
✓ No label leakage
✓ Ready for Week 5 model

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.